version: '3.5'

services:
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    restart: always
    user: "1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MONITOR_VOLUME_DIRECTORY:-.}/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ${MONITOR_VOLUME_DIRECTORY:-.}/prometheus/data:/opt/bitnami/prometheus/data
    ports:
      - "9090:9090"

  pyroscope:
    container_name: pyroscope
    image: grafana/pyroscope:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4040:4040"

  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${MONITOR_VOLUME_DIRECTORY:-.}/alloy/data:/var/lib/alloy/data
      - ${MONITOR_VOLUME_DIRECTORY:-.}/alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    user: "1000"
    volumes:
      - ${MONITOR_VOLUME_DIRECTORY:-.}/grafana:/var/lib/grafana
    ports:
      - "3000:3000"

networks:
  default:
    name: milvus_inf
    external: true
