global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: standalone
    static_configs:
      - targets: ['host.docker.internal:19091']
        labels:
          namespace: milvus
          app_kubernetes_io_name: milvus
          component: standalone
          container: standalone
          pod: standalone
          service: standalone
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*)'
        target_label: app_kubernetes_io_instance
        replacement: '${1}'
  - job_name: logstore
    static_configs:
      - targets: ['host.docker.internal:9998', 'host.docker.internal:9993', 'host.docker.internal:9995']