global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: standalone
    static_configs:
      - targets: ["host.docker.internal:19091"]
        labels:
          namespace: milvus
          app_kubernetes_io_instance: standalone
          app_kubernetes_io_name: milvus
          component: standalone
          container: standalone
          pod: standalone
          service: standalone
  - job_name: cluster
    static_configs:
      - targets: ["host.docker.internal:19092"]
        labels:
          namespace: milvus
          app_kubernetes_io_instance: cluster
          app_kubernetes_io_name: milvus
          component: mixcoord
          container: mixcoord
          pod: mixcoord
          service: mixcoord
      - targets: ["host.docker.internal:19093"]
        labels:
          namespace: milvus
          app_kubernetes_io_instance: cluster
          app_kubernetes_io_name: milvus
          component: proxy
          container: proxy
          pod: proxy
          service: proxy
      - targets: ["host.docker.internal:19094"]
        labels:
          namespace: milvus
          app_kubernetes_io_instance: cluster
          app_kubernetes_io_name: milvus
          component: querynode
          container: querynode
          pod: querynode
          service: querynode
      - targets: ["host.docker.internal:19095"]
        labels:
          namespace: milvus
          app_kubernetes_io_instance: cluster
          app_kubernetes_io_name: milvus
          component: datanode
          container: datanode
          pod: datanode
          service: datanode
      - targets: ["host.docker.internal:19096"]
        labels:
          namespace: milvus
          app_kubernetes_io_instance: cluster
          app_kubernetes_io_name: milvus
          component: indexnode
          container: indexnode
          pod: indexnode
          service: indexnode
      - targets: ["host.docker.internal:19097"]
        labels:
          namespace: milvus
          app_kubernetes_io_instance: cluster
          app_kubernetes_io_name: milvus
          component: streamingnode
          container: streamingnode
          pod: streamingnode
          service: streamingnode
  - job_name: logstore
    static_configs:
      - targets:
          [
            "host.docker.internal:9998",
            "host.docker.internal:9993",
            "host.docker.internal:9995",
          ]

